name: Node.js CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-node-20:
    name: Test on Node.js 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: CI=false npm run build --if-present

      - name: Run tests
        run: npm test -- --passWithNoTests

  test-node-22:
    name: Test on Node.js 22
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: CI=false npm run build --if-present

      - name: Run tests
        run: npm test -- --passWithNoTests
